In [1]:
from app import nba_players, nba_statistics, nba_charts, nba_analysis
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

# nba_analysis.get_cat_averages()
# nba_analysis.get_cats_probability()
# nba_analysis.get_combination_probability()
# nba_analysis.get_probability_pts_reb_ast()
# nba_analysis.get_probability_stl_blk()

def fn(player, matchup="",
            num_games=20,
            home=False,
            away=False,
            ast=None,
            reb=None,
            pts=None,
            stl=None,
            blk=None,
            pf=None,
            threes_made=None,
            triple_double=None,
            double_double=None,
            win=None):
  return nba_statistics.get_player_statistics(
    nba_players.get_id_by_player_name(player),
    matchup=nba_players.get_team_abbreviation_by_name(matchup),
            num_games=num_games,
            home=home,
            away=away,
            ast=ast,
            reb=reb,
            pts=pts,
            stl=stl,
            blk=blk,
            pf=pf,
            threes_made=threes_made,
            triple_double=triple_double,
            double_double=double_double,
            win=win
  )

# luka = pd.read_csv('players_csv/mavericks/luka.csv')
# kyrie = pd.read_csv('players_csv/mavericks/kyrie.csv')
# pj = pd.read_csv('players_csv/mavericks/pj.csv')
# gafford = pd.read_csv('players_csv/mavericks/gafford.csv')
# jones = pd.read_csv('players_csv/mavericks/jones.csv')
# hardy = pd.read_csv('players_csv/mavericks/hardy.csv')
# lively = pd.read_csv('players_csv/mavericks/lively.csv')
# brown = pd.read_csv('players_csv/celtics/brown.csv')
# tatum = pd.read_csv('players_csv/celtics/tatum.csv')
# white = pd.read_csv('players_csv/celtics/white.csv')
# porzingis = pd.read_csv('players_csv/celtics/porzingis.csv')
# holiday = pd.read_csv('players_csv/celtics/holiday.csv')
# payton = pd.read_csv('players_csv/celtics/payton.csv')
# horford = pd.read_csv('players_csv/celtics/horford.csv')

In [15]:
NUM_GAMES = 70

luka=fn('luka', num_games=NUM_GAMES)
print(luka)
kyrie=fn('kyrie', num_games=NUM_GAMES)
# pj=fn('p.j. washington', num_games=NUM_GAMES)
# gafford=fn('daniel gafford', num_games=NUM_GAMES)
# jones=fn('derrick jones jr.', num_games=NUM_GAMES)
# hardy=fn('jaden hardy', num_games=NUM_GAMES)
# lively=fn('dereck lively', num_games=NUM_GAMES)

# tatum = fn('tatum', num_games=NUM_GAMES)
# brown = fn('jaylen brown', num_games=NUM_GAMES)
# white = fn('derrick white', num_games=NUM_GAMES)
# porzingis = fn('porzingis', num_games=NUM_GAMES)
# holiday = fn('jrue holiday', num_games=NUM_GAMES)
# payton = fn('payton pritchard', num_games=NUM_GAMES)
# horford = fn('al horford', num_games=NUM_GAMES)

   SEASON_ID  Player_ID     Game_ID  GAME_DATE      MATCHUP WL  MIN  FGM  FGA  \
0      42023    1629029  0042300405 2024-06-17    DAL @ BOS  L   43   12   25
1      42023    1629029  0042300404 2024-06-14  DAL vs. BOS  W   33   12   26
2      42023    1629029  0042300403 2024-06-12  DAL vs. BOS  L   38   11   27
3      42023    1629029  0042300402 2024-06-09    DAL @ BOS  L   42   12   21
4      42023    1629029  0042300401 2024-06-06    DAL @ BOS  L   38   12   26
..       ...        ...         ...        ...          ... ..  ...  ...  ...
65     22023    1629029  0022300398 2023-12-23  DAL vs. SAS  W   32   13   27
66     22023    1629029  0022300372 2023-12-20  DAL vs. LAC  L   44    9   25
67     22023    1629029  0022300356 2023-12-18    DAL @ DEN  L   36   13   24
68     22023    1629029  0022300341 2023-12-16    DAL @ POR  W   37   15   28
69     22023    1629029  0022300321 2023-12-14  DAL vs. MIN  L   39   15   27

    FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  STL  \
0    0.480     2     9    0.222    2    5   0.400     0    12   12    5    3
1    0.462     0     8    0.000    5    7   0.714     0     5    5    5    3
2    0.407     1     7    0.143    4    4   1.000     0     6    6    6    1
3    0.571     4     9    0.444    4    8   0.500     0    11   11   11    4
4    0.462     4    12    0.333    2    5   0.400     0    10   10    1    2
..     ...   ...   ...      ...  ...  ...     ...   ...   ...  ...  ...  ...
65   0.481     5    10    0.500    8   11   0.727     2    10   12   10    1
66   0.360     2    11    0.182    8   14   0.571     1     8    9   10    1
67   0.542     6    12    0.500    6   10   0.600     3     8   11    8    0
68   0.536     4    12    0.333    6    6   1.000     2    10   12   10    1
69   0.556     2     7    0.286    7    7   1.000     1     5    6   13    2

    BLK  TOV  PF  PTS  PLUS_MINUS  VIDEO_AVAILABLE
0     0    7   3   28         -19                1
1     0    1   3   29          30                1
2     0    3   6   27           9                1
3     0    8   1   32          -3                1
4     0    4   1   30         -10                1
..  ...  ...  ..  ...         ...              ...
65    1    2   1   39          37                1
66    0    5   1   28          -4                1
67    0    3   1   38         -29                1
68    0    4   3   40          -4                1
69    0    8   2   39         -12                1

[70 rows x 27 columns]

In [6]:
nba_statistics.get_player_statistics(player_id=2544, matchup="LAL",pts=10,reb=5,ast=5, double_double=True)

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,42023,2544,0042300155,2024-04-29,LAL @ DEN,L,44,11,21,0.524,3,7,0.429,5,7,0.714,1,8,9,11,4,0,1,4,30,3,1
3,42023,2544,0042300152,2024-04-22,LAL @ DEN,L,38,9,19,0.474,3,6,0.500,5,7,0.714,0,8,8,12,2,2,2,3,26,2,1
0,22023,2544,0022301195,2024-04-14,LAL @ NOP,W,38,11,20,0.550,0,2,0.000,6,6,1.000,2,9,11,17,5,1,4,0,28,19,1
2,22023,2544,0022301155,2024-04-09,LAL vs. GSW,L,36,14,22,0.636,1,3,0.333,4,5,0.800,1,6,7,11,2,0,4,0,33,-6,1
3,22023,2544,0022301127,2024-04-06,LAL vs. CLE,W,36,10,18,0.556,1,5,0.200,3,5,0.600,0,5,5,12,1,1,5,1,24,10,1
7,22023,2544,0022301063,2024-03-29,LAL @ IND,L,35,6,12,0.500,0,3,0.000,4,4,1.000,1,9,10,8,0,0,5,1,16,-13,1
8,22023,2544,0022301055,2024-03-27,LAL @ MEM,W,35,8,14,0.571,0,1,0.000,7,11,0.636,0,14,14,12,1,0,4,1,23,33,1
9,22023,2544,0022301032,2024-03-24,LAL vs. IND,W,38,8,19,0.421,2,4,0.500,8,8,1.000,1,4,5,10,1,1,3,1,26,12,1
11,22023,2544,0022300990,2024-03-18,LAL vs. ATL,W,29,10,14,0.714,2,5,0.400,3,3,1.000,0,7,7,10,0,0,2,0,25,20,1
13,22023,2544,0022300954,2024-03-13,LAL @ SAC,L,40,6,16,0.375,2,8,0.250,4,6,0.667,1,12,13,9,2,0,5,3,18,-10,1
15,22023,2544,0022300901,2024-03-06,LAL vs. SAC,L,36,10,16,0.625,1,4,0.250,10,10,1.000,0,5,5,13,1,0,3,0,31,-3,1
16,22023,2544,0022300884,2024-03-04,LAL vs. OKC,W,31,7,14,0.500,1,3,0.333,4,5,0.800,1,10,11,8,1,0,3,1,19,14,1
20,22023,2544,0022300818,2024-02-25,LAL @ PHX,L,37,12,19,0.632,3,6,0.500,1,4,0.250,1,6,7,12,2,1,3,3,28,-8,1
28,22023,2544,0022300662,2024-01-29,LAL @ HOU,L,37,9,15,0.600,2,5,0.400,3,8,0.375,0,6,6,10,1,1,1,4,23,-11,1
29,22023,2544,0022300650,2024-01-27,LAL @ GSW,W,48,14,25,0.560,2,4,0.500,6,6,1.000,1,19,20,12,0,0,3,2,36,-6,1
32,22023,2544,0022300591,2024-01-19,LAL vs. BKN,L,34,9,22,0.409,2,5,0.400,4,5,0.800,5,6,11,5,0,0,4,1,24,-13,1
36,22023,2544,0022300516,2024-01-09,LAL vs. TOR,W,35,8,17,0.471,2,5,0.400,4,6,0.667,0,5,5,12,1,1,3,0,22,0,1
45,22023,2544,0022300370,2023-12-20,LAL @ CHI,L,37,10,18,0.556,1,3,0.333,4,4,1.000,2,8,10,9,1,2,5,0,25,-11,1
46,22023,2544,0022300359,2023-12-18,LAL vs. NYK,L,39,10,23,0.435,2,8,0.250,3,4,0.750,1,10,11,11,1,0,2,1,25,-13,1
47,22023,2544,0022300331,2023-12-15,LAL @ SAS,L,36,7,17,0.412,2,6,0.333,7,10,0.700,2,5,7,14,2,0,2,1,23,-28,1

In [ ]:
# luka.to_csv('players_csv/mavericks/luka.csv', index=False)
# kyrie.to_csv('players_csv/mavericks/kyrie.csv', index=False)
# pj.to_csv('players_csv/mavericks/pj.csv', index=False)
# gafford.to_csv('players_csv/mavericks/gafford.csv', index=False)
# jones.to_csv('players_csv/mavericks/jones.csv', index=False)
# hardy.to_csv('players_csv/mavericks/hardy.csv', index=False)
# lively.to_csv('players_csv/mavericks/lively.csv', index=False)

# tatum.to_csv('players_csv/celtics/tatum.csv', index=False)
# brown.to_csv('players_csv/celtics/brown.csv', index=False)
# white.to_csv('players_csv/celtics/white.csv', index=False)
# porzingis.to_csv('players_csv/celtics/porzingis.csv', index=False)
# holiday.to_csv('players_csv/celtics/holiday.csv', index=False)
# payton.to_csv('players_csv/celtics/payton.csv', index=False)
# horford.to_csv('players_csv/celtics/horford.csv', index=False)
# nba_players.check_csv_file()

'players_csv/nba_players.csv'

In [18]:
player_1 = {
  'pts': 15,
  'reb': 0,
  'ast': 10,
  'stl': 0,
  'blk': 0,
  'total_pra': 0,
  'total_sb': 0
}

player_2 = {
  'pts': 15,
  'reb': 0,
  'ast': 0,
  'stl': 0,
  'blk': 0,
  'total_pra': 0,
  'total_sb': 0
}

player_3 = {
  'pts': 8,
  'reb': 4,
  'ast': 0,
  'stl': 0,
  'blk': 0,
  'total_pra': 0,
  'total_sb': 0
}
player_4 = {
  'pts': 15,
  'ast': 10,
  'stl': 0,
  'blk': 0,
  'win': True
}

player_5 = {
  'pts': 15,
  'reb': 0,
  'ast': 0,
  'stl': 0,
  'blk': 0,
}

player_6 = {
  'pts': 8,
  'reb': 4,
  'ast': 0,
  'stl': 0,
  'blk': 0,
}

# players = [player_1, player_2, player_3]

# luka=fn('luka')

# nba_analysis.get_cat_averages()
# nba_analysis.get_cats_probability(kyrie, reb=4)
nba_analysis.get_combination_probability([kyrie, luka], [player_1, player_2], combine='all')
# nba_analysis.get_probability_pts_reb_ast()
# nba_analysis.get_probability_stl_blk()

'Times Achieved / Total Games, 1/57 = 1.7543859649122806 %'

In [ ]:
nba_analysis.get_probability_table_combos(logs=[luka, kyrie])
# nba_analysis.get_cats_probability(fn('luka', matchup='celtics'), player_1)
# nba_analysis.get_cats_probability(nba_statistics.get_player_statistics(2544), ...player_1)
# stats = nba_statistics.get_player_statistics(2544)

# nba_analysis.get_cats_probability(stats, **player_4)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62
FG3M,0.0 %,98.25 %,92.98 %,84.21 %,73.68 %,61.4 %,50.88 %,36.84 %,28.07 %,14.04 %,7.02 %,1.75 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,NaN
PTS,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,98.25 %,96.49 %,94.74 %,92.98 %,91.23 %,89.47 %,87.72 %,85.96 %,84.21 %,82.46 %,80.7 %,78.95 %,77.19 %,75.44 %,73.68 %,71.93 %,70.18 %,68.42 %,66.67 %,64.91 %,63.16 %,61.4 %,59.65 %,57.89 %,56.14 %,54.39 %,52.63 %,50.88 %,49.12 %,45.61 %,40.35 %,36.84 %,35.09 %,33.33 %,29.82 %,24.56 %
REB,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,98.25 %,96.49 %,94.74 %,92.98 %,87.72 %,77.19 %,59.65 %,43.86 %,29.82 %,24.56 %,14.04 %,8.77 %,7.02 %,1.75 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,NaN
AST,0.0 %,0.0 %,0.0 %,98.25 %,96.49 %,94.74 %,92.98 %,91.23 %,89.47 %,87.72 %,84.21 %,80.7 %,71.93 %,63.16 %,45.61 %,31.58 %,26.32 %,17.54 %,12.28 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,NaN
STL,94.74 %,77.19 %,56.14 %,36.84 %,8.77 %,5.26 %,1.75 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,NaN
BLK,56.14 %,21.05 %,7.02 %,3.51 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,0.0 %,NaN